#!/bin/bash

# This script updates the current LPiL-TeX packages into the local
# TEXMFLOCAL

# Ask for the TEXMFLOCAL value from the TeXLive Manager (tlmrg)
TEXMFLOCAL=`tlmgr conf | grep TEXMFLOCAL | cut -d= -f2`

######################################################################
# ConTeXt
# Copy the current ConTeXt version over to the local TEXMFLOCAL directory
mkdir -p $TEXMFLOCAL/tex/context/third
cp -R commDiag $TEXMFLOCAL/tex/context/third

# Now we update context's file search database
context --generate
